# Generated by Django 4.1.4 on 2023-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummyform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='photographs')),
            ],
            options={
                'verbose_name_plural': 'Form',
                'db_table': 'contact_forms',
            },
        ),
    ]
